### ISSUE TITLE
Double DESTDIR in manpage install

### ISSUE THREAD

**Issue by alexaring** [mcr/unstrung#18]
Got some $(DESTDIR)/$(DESTDIR) while installing manpages, I fixed it with the following patch:

Subject: [PATCH] Makefile: remove twice DESTDIR for man pages

The DESTDIR will be appended in install rules of
"programs/Makefile.program" by using MANDIR# declartions which use
MANTREE. This patch removes the DESTDIR from MANTREE, otherwise the
there is some kind of $(DESTDIR)/$(DESTIR) behaviour.
---
 Makefile.inc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Makefile.inc b/Makefile.inc
index 156c3554b5fd..3d5bfd9429a9 100644
--- a/Makefile.inc
+++ b/Makefile.inc
@@ -14,7 +14,7 @@ HOSTFLAGS=-m32
 USE_OBJDIR?=false
 XMLTO=xmlto
 
-MANTREE=${DESTDIR}/usr/share/man
+MANTREE=/usr/share/man
 INSTALL=install
 INSTMANFLAGS=-D
 INSTBINFLAGS=-D

**Comment by mcr** [comment]
okay, agreed. I was confused why this wasn't a pull request...
I had to apply this patch manually.
